### PR TITLE
fix(fela-plugin-extend): don't throw on undefined items in extend array

### LINKED ISSUE #657: fela-plugin-extend crushes on undefined
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela     | 6.1.7   |
| react-fela     | 7.2.0   |
| fela-plugin-extend     | 6.0.11   |

-------------------
#### Description
Passing `undefined` to the `extend` array throws a reference error about `hasOwnProperty of undefined`.

#### Steps to reproduce
```js
const style = theme => ({
  extend: [ undefined, ],
});
```

#### Expected Behavior
`undefined` should just be discarded

### PR DESCRIPTION
**Pull request by TxHawks**
## Description
Fixes #657 where `fela-plugin-extend` would throw when the `extend` key in a style object was an array with a `null` or `undefined` item inside it.

Adds a test

## Packages

fela-plugin-extend

## Versioning

- [ ] Major
- [ ] Minor
- [x] Patch

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

### CODE REVIEW

File: packages/fela-plugin-extend/src/index.js [hunk 1]
```diff
@@ -22,7 +22,10 @@ function removeUndefined(style: Object): Object {
 
 function extendStyle(style: Object, extension: Object): void {
   // extend conditional style objects
-  if (extension.hasOwnProperty('condition')) {
+  if (
+    extension &&
+    Object.prototype.hasOwnProperty.call(extension, 'condition')
```
Comment (rofrischmann) [inline packages/fela-plugin-extend/src/index.js]: What's the benefit of calling it this way instead of just `extension.hasOwnProperty('condition')`?

Comment (TxHawks) [reply packages/fela-plugin-extend/src/index.js]: It's not a big deal, but if someone uses `Object.create(null)` to create a lightweight map without the entire object prototype, `.hasOwnProperty` would not exist and the code would throw an `hasOwnProperty is not a function` TypeError.

So, if somene did:
```js
<FelaComponent 
  style={Object.assign(Object.create(null), { extend: [ /* ... */ ], })}
>
```

that would error out.

I wouldn't necessarily bother with this kind of thing in app code, but I feel library code should be as robust as possible and I don't really see any down side to it.

Comment (TxHawks) [reply packages/fela-plugin-extend/src/index.js]: Let me know if you'd like me to change it back or release it like this

Comment (rofrischmann) [reply packages/fela-plugin-extend/src/index.js]: Oh sure not, that makes sense - didn't know it =)

**Comment by TxHawks** [comment]
Can't release because flow errors out on unrelated issues

**Comment by rofrischmann** [comment]
Hmmmm, experienced the same issue with Flow in another repo and I couldn't even ignore them. Feel free to disable flow for the release

**Comment by TxHawks** [comment]
updated the changelog, but I can't merge it without you approving it
