### PR TITLE
Replace unallowed symbols in class name with underscore

### LINKED ISSUE #596: fela-monolithic with prettySelectors: true doesn't escape characters in displayName
**Type**: Bug

| Packages | Version |
| -------- | ------- |
| fela | ^6.1.9 |
| fela-dom | ^7.0.9 |
| fela-monolithic | ^5.0.23 |
| react-fela | ^7.3.1 |

-------------------
#### Description
`fela-monolithic` with `prettySelectors: true` doesn't escape characters in class name such as parenthesis.

#### Steps to reproduce

1. Create component
2.  Add displayName with symbols which needs to be escaped in class name (e. g. parenthesis)
2. Use createComponent to add styles

[repository with minimal reproducable example](https://github.com/Nitive/fela-display-name-bug)

#### Expected Behavior
displayName is escaped

#### Actual Behavior
displayName is not escaped

### PR DESCRIPTION
**Pull request by Nitive**
Fixes #596

## Description
Replace unallowed symbols with underscore for class names based on function `.name` or component `.displayName`.

I wanted to escape class names at first, but this approach has two downsides:
1. We need to add `css.escape` dependency to polyfill CSS.escape. It would be used for development only, but still
2. We need to escape it in style tag, but keep unescaped name in dom attribute. It adds extra troubles

#### Patch

- fela-bindings
- react-fela
- preact-fela
- inferno-fela

## Checklist

- [x] The code was formatted using Prettier (`yarn run format`)
- [x] The code has no linting errors (`yarn run lint`)
- [x] All tests are passing (`yarn run test`) 
- [x] There are no flow-type errors (`yarn run flow`)

#### Changes
If one of the following checks doesn't make sense due to the type of PR, just check them.

- [x] Tests have been added/updated
- [x] Documentation has been added/updated
- [x] My changes have proper flow-types

### CODE REVIEW

File: packages/fela-bindings/src/__tests__/__snapshots__/createComponentFactory-test.js.snap [hunk 1]
```diff
@@ -889,6 +889,48 @@ Array [
...
+    .rule_connect_Component___abrv9k {
+        font-size: 16
+    }
+</style>",
+  <rule>
+    <rule
+        _felaTheme={Object {}}
+    >
+        <connect(Component)
+            className="rule_connect_Component___abrv9k"
```
Comment (Nitive) [inline packages/fela-bindings/src/__tests__/__snapshots__/createComponentFactory-test.js.snap]: Readable class name in common cases

File: packages/fela-bindings/src/__tests__/__snapshots__/createComponentFactory-test.js.snap [hunk 2]
```diff
@@ -889,6 +889,48 @@ Array [
 ]
 `;
 
+exports[`Creating Components with a Proxy for props from Fela rules should replace rare unallowed symbols in className with underscore 1`] = `
+Array [
+  "<style>
+    .rule_1_______________abrv9k {
```
Comment (Nitive) [inline packages/fela-bindings/src/__tests__/__snapshots__/createComponentFactory-test.js.snap]: Unique, but unreadable class name, because most of the displayName contains unallowed symbols (`displayName = '1!@#$%^&*{}/=\\'`)

**Comment by rofrischmann** [comment]
Thanks for the PR :)
