### PR TITLE
fela-combine-arrays fix

### LINKED ISSUE #445: [fela-combine-arrays] Plugin seems to break nested selectors output with latest versions.
**Version**: 6.0.3
**Environment**: DOM / Server / Both
**Type**: Bug

Repro commit:
https://github.com/aga5tya/fela/commit/65ef29e88bb6ef2911254a6921391e268ee331a1

screen shot 2017-10-23 at 12 30 48 am

Removing the plugin everything works fine. cc/ @rofrischmann

### PR DESCRIPTION
**Pull request by rofrischmann**
#### Patch
- fela-combine-arrays

### CODE REVIEW

File: packages/fela-dom/src/dom/rehydration/__tests__/rehydrate-test.js [hunk 1]
```diff
@@ -30,7 +30,6 @@ describe('Rehydrating from DOM nodes', () => {
 
     document.head.innerHTML = renderToMarkup(serverRenderer)
 
-    console.log(document.head.innerHTML)
```
Comment (HugoGiraudel) [inline packages/fela-dom/src/dom/rehydration/__tests__/rehydrate-test.js]: Classic. 😄
